### ISSUE TITLE
train result question

### ISSUE THREAD

**Issue by renhui19931001** [yiwenguo/Dynamic-Network-Surgery#13]
using the dynamic network surgery ,I can train lenet5 on mnist database reach 99.07% accuracy,but when I   
 test the compression results,I find that Many parameters are not 0, but are very close to 0.The program did not write the corresponding zero program ? The training results from and downloaded caffemodel from your project there are some differences.can you tell me how to fix it or how to use the dynamic network surgery train lenet5 well?

**Comment by renhui19931001** [comment]
OO,I have solve the problem:1.c_rate is the param related to ak,bk in paper,so we should not set 4 to the first convolution,and it cause the result of dosen't convergence.And about the weight ,I found that there is weightTmp in the compress_conv_layer,and it is used to do convolution but not weight.

**Comment by chengsonghust** [comment]
But how to get the weightTmp from caffemodel file?
