### ISSUE TITLE
train problem 

### ISSUE THREAD

**Issue by botaichang** [yiwenguo/Dynamic-Network-Surgery#16]
when i finetune resnet model, I got this error: 
I0814 15:49:26.345660  3407 net.cpp:774] Copying source layer conv1
F0814 15:49:26.345674  3407 net.cpp:777] Check failed: target_blobs.size() == source_layer.blobs_size() (4 vs. 2) Incompatible number of blobs for layer conv1

it may because there are only 2 items(weights and bias) in convolution layer's param in the original caffemodel, but cconvolution layer has 4 items. when it make copy from source layer to target cconvolution layer, it got error. 

Could you give an example of the prototxt ? Thank you!

**Comment by yiwenguo** [comment]
Hi, @melchior-note . Better use the [command line interface](http://caffe.berkeleyvision.org/tutorial/interfaces.html) instead with this repository and then you probably won't have this problem. For the Python interface, you can refer to #1 for a solution.

**Comment by botaichang** [comment]
I do use the command line interface, but it got this error because the param blob size is different between the original caffemodel and compressed caffemodel. If i change the conv layer's name, it will not get this error but we can not finetune original weights.

**Comment by yiwenguo** [comment]
Sorry I just found that your net.cpp file is probably different with the file provided in this repository. Please double-check.
