### ISSUE TITLE
c_rate setting

### ISSUE THREAD

**Issue by ALHOLA** [yiwenguo/Dynamic-Network-Surgery#2]
Hello, Is there any algorithm or formula for setting the c_rate value in the cconvolution_param or cinnerproduct_param.I tried out different values and this repo works weird with float c_rate values. The value of 4 in the sample prototxt for lenet doesn't work in my case. Can you help to come up with the right value for c_rate?

**Comment by akamaster** [comment]
I don't think authors are going to reply. Moreover, I think results of the paper are not reproducible.

**Comment by yiwenguo** [comment]
In the example for LeNet-5, we didn't really mean that the c_rate values for different layers should all be set as 4. Of course you can try float (and even negative float) c_rate values. Can @ALHOLA provide more details on the weird results? Thanks.

**Comment by akamaster** [comment]
Provide the right values for c_rate so that results of your NIPS paper can be reproducded. Prototxt file would be even better.

**Comment by yiwenguo** [comment]
@akamaster,  Indeed, the hyper-parameters are not easy to tune. Please be patient. I did some experiments this morning and maybe you can follow. Taking LeNet-5 as an example, you can try something like:
 {conv1: c_rate (1), iter_stop (14000); conv2: c_rate (3), iter_stop (14000); ip1: c_rate (4), iter_stop (10000); ip2: c_rate (2.5), iter_stop (10000)}
 {conv1: c_rate (1), iter_stop (14000); conv2: c_rate (3), iter_stop (12000); ip1: c_rate (4), iter_stop (10000); ip2: c_rate (2.5), iter_stop (8000)} 
 {conv1: c_rate (2.5), iter_stop (14000); conv2: c_rate (3), iter_stop (14000); ip1: c_rate (4), iter_stop (14000); ip2: c_rate (2.5), iter_stop (14000)}.
