### ISSUE TITLE
Unable to train new model

### ISSUE THREAD

**Issue by siftr** [yiwenguo/Dynamic-Network-Surgery#3]
on training a model following error occurs - 
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0327 18:35:26.106482 11582 layer_factory.hpp:68] Check failed: registry.count(type) == 0 (1 vs. 0) Layer type CConvolution already registered.
*** Check failure stack trace: ***
Aborted (core dumped)

Any idea how to fix this.??

**Comment by yiwenguo** [comment]
I think it has something to do with the cudnn part, now I have temporarily fixed it.
