### ISSUE TITLE
The compile problem

### ISSUE THREAD

**Issue by xiaoboCASIA** [yiwenguo/Dynamic-Network-Surgery#4]
Hello! Thanks for your work. Could you help me to fix the compile problem? When I make all -j8, the errors src/caffe/layers/compress_conv_layer.cpp: In instantiation of ‘void caffe::CConvolutionLayer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/compress_conv_layer.cpp:205:1:   required from here
src/caffe/layers/compress_conv_layer.cpp:81:36: error: ‘class caffe::CConvolutionLayer<float>’ has no member named ‘iter_’
     if (this->std==0 && this->iter_==0){      
                                    ^
src/caffe/layers/compress_conv_layer.cpp:118:26: error: ‘class caffe::CConvolutionLayer<float>’ has no member named ‘iter_’ will happen. Is the relevent .hpp file missing? I can not find the compress_conv_layer.hpp in the package. Thanks for your help!

**Comment by yiwenguo** [comment]
Hi @xiaoboCASIA , I guess you are using a later version of Caffe than mine. In this repository with classical Caffe, the CConvolution class is defined in the "vision_layers.hpp" file. To fix this compile problem, you can either use a classical Caffe as I did or creat a new file of "compress_conv_layer.hpp" accordingly.

**Comment by ouceduxzk** [comment]
@xiaoboCASIA  does you fix your problems ?
