### ISSUE TITLE
help

### ISSUE THREAD

**Issue by LXWDL** [yiwenguo/Dynamic-Network-Surgery#6]
I do not understand what you mean by the following sentence?
“Dynamic network surgery is a very effective method for DNN pruning. To better use it with python and matlab, you may also need a classic version of the Caffe framework. ”
 Can you explain it in detail? Because you provide the caffe code is missing examples and matlab file, in the translation of the time there will be a lot of problems, you mean to use your caffe file to replace you below to the caffe code in the document or?

**Comment by yiwenguo** [comment]
Hi @LXWDL . It should be smooth to use the [command line interface](http://caffe.berkeleyvision.org/tutorial/interfaces.html) directly with this repo. What I wanna say is about using the Python and MATLAB interfaces. You can copy the matlab and python directories from the classic Caffe to this repo before running "make all" for enabling these two interfaces.
