### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by ghost** [yiwenguo/Dynamic-Network-Surgery#9]
thanks for your work, I use your woke to pruning resnet18, but I find it does not work, did your share a solver prototxt to pruning network?

**Comment by ghost** [comment]
do you train from scatch or finetune?

**Comment by yiwenguo** [comment]
Hi @pby5 . In order to prune resnet, you need to get a pre-trained dense model beforehand and follow the Caffe finetuning pipeline to run surgeries.
